export const LYRICS_GET = 'LYRICS_GET';
export const LYRICS_GET_SUCCESS = 'LYRICS_GET_SUCCESS';
export const LYRICS_GET_FAILED = 'LYRICS_GET_FAILED';

export const LYRICS_SUGGEST = 'LYRICS_SUGGEST';
export const LYRICS_SUGGEST_SUCCESS = 'LYRICS_SUGGEST_SUCCESS';
export const LYRICS_SUGGEST_FAILED = 'LYRICS_SUGGEST_FAILED';
